cloudwatch-exporter.tf, ecr-exporter.tf, kiam.tf, locals.tf, main.tf, outputs.tf, prometheus.tf, resources/prometheusrule-alerts/Custom-Alerts.md, resources/prometheusrule-alerts/application-alerts.yaml, resources/prometheusrule-alerts/node-alerts.yaml, templates/oauth2-proxy.yaml.tpl, templates/prometheus-operator.yaml.tpl, variables.tf
In order to achieve the migration of the Prometheus resources to their own terraform module we had to create a new repo (this one) and move all resources from [cloud-platform-components](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform-components/prometheus.tf) to here.
=> Prometheus Terraform Migration

main.tf, prometheus.tf, templates/prometheus-operator.yaml.tpl, templates/thanos-values.yaml.tpl, thanos.tf, variables.tf
Thanos sidecar was added in our last release of (0.0.5) Prometheus terraform module. The sidecar allows us to push metrics to S3 bucket, only that! What if we want to visualise these metrics from the S3 bucket? If we want to compact them? If we want to create alerts/rules from them? 
This PR installs a Thanos Helm Chart (developed by banzaicloud) which deploys another Thanos components: Bucket, Check, Compactor, Query, Rule
For the time being these components are not going to be exposed, they will reside/live inside the cluster and the way how to access them will be through port-forward. Later on, in future releases, Ingresses and proxy-auths will be set up.
Another important change included is externalLabels for Prometheus. These labels allow us to differentiate Prometheuses from each …
=> Thanos Helm Chart

templates/prometheus-operator.yaml.tpl
We are experiencing memory problems with Prometheus, because of this we're updating retention to 24h. The metrics are saved in S3 using Thanos.
=> Updated retention period to 1d

resources/cloudwatch-exporter.yaml
This module is referencing a file that doesn't exist (CloudWatch values file), [check it here](https://github.com/ministryofjustice/cloud-platform-terraform-prometheus/blob/master/cloudwatch-exporter.tf#L13). 
This PR adds the missing file.
=> Added forgotten cloudwatch values file

cloudwatch-exporter.tf
Because now we are using Prometheus/CloudWatch from within a module we must use `path.module` to reference files.
=> Implemented `path.module` for a reference

cloudwatch-exporter.tf, ecr-exporter.tf, outputs.tf, prometheus.tf, templates/prometheus-operator.yaml.tpl, thanos.tf, variables.tf
Added nodeAffinity capabilities to Prometheus in order to specify in which instance class it needs to be deployed. This requirement comes from Prometheus resources problem we are having. 
It applies some format to the terraform files (`terraform fmt`)
=> Added NodeAffinity to Prometheus and ran terraform format

main.tf, prometheus.tf
Part of our Helm3 upgrade requires setting up repository explicitly, otherwise, we face [this issue](https://github.com/terraform-providers/terraform-provider-helm/issues/448).
=> Setting repository explicitly

resources/cloudwatch-exporter.yaml
As it is giving "Context Deadline Exceeded" error for cloud-watch in prometheus.
=> Updating cloudwatch timeout: 60s

resources/cloudwatch-exporter.yaml
For some metrics which are updated very infrequently (such as S3/BucketSize), Prometheus
may refuse to scrape them if this is set to true.
=> Updated cloudwatch_exporter set_timestamp to false

resources/prometheusrule-alerts/node-alerts.yaml
WHAT
Increase critical failure wait time to 5 mins and add a warning error for 3 mins to go to low priority alarms
WHY
We have had a number of triggers for this alarm, which have resolved by itself. Nginx resolves the error by correcting the config compared to the other ingress controller pods. This trigger was set to 1 min, therefor triggering before nginx can resolve. New alert will trigger after 3 mins and high priority critical after 5 mins.
=> Add warning nginx reload failure and increase critical alert threshold to 5 mins 

templates/prometheus-operator.yaml.tpl
Deploying the latest version of Thanos container (v0.11.0). They improved performance (and much more things, complete list [here](https://github.com/thanos-io/thanos/blob/master/CHANGELOG.md#v0110---20200302)) and hopefully can help us to manage the memory overload.
=> Thanos to the latest version, where they have better performance

resources/prometheusrule-alerts/application-alerts.yaml
Why:
[Update "KubeAPILatencyHigh" Alerts#1797](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1797)
[Investigate the high KubeAPILatencyHigh alarms#1717](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1717)
4 custom alerts created:
2 - warning (1 for IngressPost KubeAPILatency alerts, 1 for remaining KubeAPILatency alerts
2 - critical (1 for IngressPost KubeAPILatency alerts, 1 for remaining KubeAPILatency alerts
Ingress alerts set to :
-  over 10 seconds for 5minutes , warning
-   over 30 seconds for 10minutes , warning
To do - Update run-book with  custom alerts description and change run-book links here
=> add 4 new KubeAPILatency alerts - separating out ingress post alerts …from the others

resources/prometheusrule-alerts/README.md
WHAT
Change the md to README.md and add custom api high latency alarms
WHY
Will link the readme on our runbooks and custom alarms needed as the api call for ingress post is taking longer due to the validation hook we are using on the nginx ingress controller to validate ingress configs before applying
=> Add custom high latency alarm docs

templates/prometheus-operator.yaml.tpl
WHAT
Silence default api high latency alarm 
WHY
We have new custom alerts for this that separates out ingress post api calls with longer trigger values and new alarms for all other api calls
=> Silence high latency alarms as new custom alerts created

metrics-server.tf
This PR moves metrics-server terraform helm resource into the monitoring module, it looks more related to monitoring and useful to be within a module.
=> Migrating metrics server to the monitoring module

templates/prometheus-operator.yaml.tpl
This mutes AggregatedAPIDown, which get triggered in the latest Prometheus Operator upgrade we did for the Helm Chart.
As you can see in https://github.com/helm/charts/issues/22278 and https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/397 looks to be happening for k8s versions < 1.18
=> Mute AggregatedAPIDown alarm

cloudwatch-exporter.tf, templates/cloudwatch-exporter.yaml
This was done on the flight in order to fix helm-3 issues with the cloudwatch exporter's helm chart.
=> Upgraded cloudwatch to the latest 

prometheus.tf, thanos.tf
Otherwise, we face in EKS:
```
Error: Invalid index
on .terraform/modules/monitoring/prometheus.tf line 309, in module "iam_assumable_role_grafana_datasource":
309:   role_policy_arns              = [var.eks ? aws_iam_policy.grafana_datasource.0.arn : "" ]
|----------------
| aws_iam_policy.grafana_datasource is empty tuple
The given key does not identify an element in this collection value.
Error: Invalid index
on .terraform/modules/monitoring/thanos.tf line 101, in module "iam_assumable_role_monitoring":
101:   role_policy_arns              = [var.eks ? aws_iam_policy.monitoring.0.arn : ""]
|----------------
| aws_iam_policy.monitoring is empty tuple
The given key does not identify an element in this collection value.
```
NOTE: This change only applies to EKS
=> Fixed conditional in order to avoid empty tuple

README.md, ecr-exporter.tf, metrics-server.tf, prometheus.tf, variables.tf
This variable was needed when we were using Helm 2, it was the way to tell Helm Chart inside our terraform modules to wait for tiller before getting installed.
Now we are using Helm 3 and there is not tiller in the clusters.
=> Deleted dependence_deploy variable

templates/prometheus-operator.yaml.tpl
This is due to Grafana 7.0.2 released with important security fix
https://grafana.com/blog/2020/06/03/grafana-6.7.4-and-7.0.2-released-with-important-security-fix/?utm_source=grafana_news&utm_medium=rss
=> Upgrade grafana to 7.0.2

resources/prometheusrule-alerts/application-alerts.yaml
At the moment this alarm triggers a lot without action. To ensure there
is always action I have bumped the trigger to exceed 17 seconds.
This value is one above all other past KubeAPILatencyWarning-IngressPost
alarms that had no action.
=> Bump KubeAPILatencyWarning-IngressPost alarm to 17 seconds

resources/prometheusrule-alerts/node-alerts.yaml
Why:
[Amend nginx alarm to show which pod has failed#2188](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2188):
"kube_deployment_status_replicas_available" - always seems to return information concerning the prometheus pod rather than the "ingress-controllers" pod - which is actually the one that has gone down/failed etc. See here for example https://mojdt.slack.com/archives/C8QR5FQRX/p1596764130004800
I have included:
-  alert for warning - when 1 or more pods have "failed" (sum by pod).
-  alert for warning - when 1 pods have "pending" or "unknown" status (sum by pod).
-  alert for critical - when more than 5 pods have "failed" (sum by namespace).
=> Update NginxIngressPodDown alerts - incorrect info returned

resources/prometheusrule-alerts/application-alerts.yaml
The ingress-post API latency alarm triggers on a regular occurrence.
This happens because of the great load we place on our load balancers.To
fix this all teams in the cluster will get there own ingress
controllers, with their own load balancers.
As this work will take a while to adopt, it is necessary for us to
increase the warning aspect of this alarm to 30, which in turn will mean
increasing the critical alarm to 50.
=> Bump latency for ingress post alarm

templates/oauth2-proxy.yaml.tpl, templates/prometheus-operator.yaml.tpl
Specified a custom annotation within ingress metadata in order to force them the use of monitoring ingress controller rather than the default one
=> Explicitly specified which ingress controller to use.

resources/prometheusrule-alerts/node-alerts.yaml
Now alerts are not targeting certain pods within the namespace, they are targetting everything. This is one as part of our nginx ingress implementation.
=> Update ingress alerts to included everything within the namespace

templates/oauth2-proxy.yaml.tpl, templates/prometheus-operator.yaml.tpl
As we discussed in the SU, we agreed all traffic should go through the default ingress controller.
=> Removed ingress classes, we want to use the default ingress controller

prometheus.tf, templates/oauth2-proxy.yaml.tpl
Breaking changes outlined in this README:
https://github.com/helm/charts/tree/master/stable/oauth2-proxy#to-300
This requires us to specify that we don't want to enable a service
account from IAM.
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/2078
=> Bump prometheus and alertmanager chart proxies to 3.2.2

README.md, prometheus.tf, resources/prometheus-infrastructure.yaml, templates/prometheus-operator.yaml.tpl, variables.tf
- add(prometheus): New Prometheus in place to manage the infrastructure rules.
- add(oidcProxy): In order to access to the new Prometheus we need to enable another OIDC Proxy
- remove(kubeDNSchecks): We are not using CoreDNS across EKS and KOPS
=> New Prometheus, new OIDC Proxy and Remove kubeDNS checks.

templates/prometheus-operator.yaml.tpl
Otherwise, we see:
```
Error: ---> error converting YAML to JSON: yaml: line 911: did not find expected key # Default values for prometheus-operator.                                                                                                                                                                        
ruleSelector:                                                                                                                                                                                                                                                                                 
matchLabels: …
```
=> Fixed indentation

ecr-exporter.tf, prometheus.tf
As part of https://github.com/ministryofjustice/cloud-platform/issues/2369 we are setting up the network policies within the terraform module, so test clusters can also have them.
=> Moved network policies from environment repo to the terraform module

templates/cloudwatch-exporter.yaml
Sometimes the service is timing out before actually getting the results, you can see the gaps in Prometheus.
=> Increased timeout for cloudwatch exporter

resources/prometheusrule-alerts/application-alerts.yaml, resources/prometheusrule-alerts/node-alerts.yaml
Some of our custom rules were not picked up because of labelling issues. This PR adds the required labels to Prometheus.
=> Added custom labels (release: prometheus-operator) for Prometheus rules

resources/prometheusrule-alerts/application-alerts.yaml
Change all custom alarms to use the new NS annotation of `cloud_platform_out_of_hours_alert="true"`
=> Change all custom alarm expressions based on new annotation

resources/prometheusrule-alerts/README.md, resources/prometheusrule-alerts/node-alerts.yaml
Why:
[Check all custom Prometheus Rules #2475](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2475)
removal of LoadBalancer5XXCountHigh alert - addition of latency and http request error alerts for ingress-controller pods
The 1% of all requests for 5xx and the 300ms for latency are a bit arbitrary at the moment - however we can tweak as and when it becomes apparent problems are taking place (and they can act as an advance indicator).
=> removal of LoadBalancer5XXCountHigh alert - addition of latency and http request error alerts

resources/prometheusrule-alerts/application-alerts.yaml
Why:
[Check all custom Prometheus Rules #2475](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2475)
Please see https://mojdt.slack.com/archives/C514ETYJX/p1604495631237800
https://sysdig.com/blog/how-to-monitor-coredns/
=> updateprometheus custom alerts  new alert for coreDNS

resources/prometheusrule-alerts/node-alerts.yaml
The alarms are far too noisy and don't provide a path to resolution.
After consulting with the team, it has been decided we should remove
these alarms and re-assess how we can perform anomaly detection.
=> Remove nginx ingress 5xx alarms

thanos.tf
With the new version of Prometheus Operator there was a rename of the service account. Because IRSA is tied to SA the role wasn't attached anywhere and therefore the upload to the S3 bucket wasn't working.
=> Update IRSA for EKS

prometheus.tf
We are getting:
```
Warning: Interpolation-only expressions are deprecated
on .terraform/modules/prometheus/prometheus.tf line 97, in resource "helm_release" "prometheus_operator":
97:     alertmanager_routes                        = "${join("", data.template_file.alertmanager_routes.*.rendered)}" 
```
This PR fixes it.
=> Update prometheus.tf to avoid interpolation warning

templates/prometheus-operator.yaml.tpl
to check (see cluster raz-test):
```
NAMESPACE    NAME                                                                                                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
monitoring   alertmanager-prometheus-operator-kube-p-alertmanager-db-alertmanager-prometheus-operator-kube-p-alertmanager-0   Bound    pvc-03889d6a-3cb4-483a-9bd1-2d055863033d   1Gi        RWO            gp2-expand     67s
```
silence any alarm
```
bash-5.0# kubectl -n monitoring delete pod alertmanager-prometheus-operator-kube-p-alertmanager-0
```
when the pod comes back, the silenced alarm must still be present
=> alertmanager storage typo

templates/prometheus-operator.yaml.tpl
NodeFilesystemSpaceFillingUp has been alerting a lot on low-priority-alarms and it requires a prune of docker images or gets resolved by itself.
The cause of this alert is normally when we create a new node and lots of pods are being created. This alert is a prediect_linear which notifies us that at this rate disk space will be used up in the next 4 hours. So far it has not used up all the space. This is due to a garbage collection action runs on the nodes at 80%+ usage. 
There is also alarms for when/if disk space is below 5%
=> Set NodeFilesystemSpaceFillingUp alert to NULL

resources/prometheusrule-alerts/README.md, resources/prometheusrule-alerts/node-alerts.yaml
Why:
"irate should only be used when graphing volatile, fast-moving counters. <b>Use rate for alerts and slow-moving counters</b>, as brief changes in the rate can reset the FOR clause and graphs consisting entirely of rare spikes are hard to read."
See [irate()](https://prometheus.io/docs/prometheus/latest/querying/functions/#irate)
and [rate()](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate)
=> cpu-high and critical change irate to rate

resources/prometheusrule-alerts/README.md, resources/prometheusrule-alerts/node-alerts.yaml
Trying to get the trade off between noisy cpu alerts and actually notifying cloud-platforms of a real problem right
=> cpu - less noisy alerts

resources/prometheusrule-alerts/README.md, resources/prometheusrule-alerts/node-alerts.yaml
WHAT
Change disk-space alert to ignore snap mountpoints
WHY
For the kops 1.18 upgrade, the image for the nodes changes from debian to Ubuntu. 
Ubuntu images create /snap/* mountpoints used for Ubuntu snap packages. We do not use these and they are almost always 100% full even with garbage collection running. 
This alert will ignore all /snap* mountpoints but alert on all others. There is a separate specific alert for /root.
=> Change disk-space alert to ignore snap mountpoints

ecr-exporter.tf
Unfortunately, ECR is using the default serviceAccount to run the pod instead of its own. This PR links the AWS role to the default SA
=> Setting IRSA for ECR with default service account

prometheus.tf, templates/prometheus-operator.yaml.tpl
`io1-expand` is in EKS already, we can set the prometheus one in either side (EKS/kops) to use it.
=> Setting static storage class to io1-expand everywhere (EKS and KOPS)

README.md, locals.tf, prometheus.tf, templates/oauth2-proxy.yaml.tpl, templates/prometheus-operator.yaml.tpl, variables.tf
This is in light of the EKS migration
-  Add external-dns annotation to grafana/kibana/prometheus/alertmanager
- Configure cluster-specific and live_domain hosts in ingress, for Prometheus and alert manager
- Create ingress to redirect_grafana while accessing live_domain,
cannot be set up as we did for Prometheus and alert manager as GF_SERVER_ROOT_URL supports only one URL.
This is related to:
https://github.com/ministryofjustice/cloud-platform/issues/3007
=> Implement URLs for monitoring stack

templates/prometheus-operator.yaml.tpl
The usage of the prometheus container has risen in range of 34000Mi and without increasing this limit, the pod would terminate with OOMKilled
=> Increase prometheus container memory to 60000Mi

prometheus.tf, templates/oauth2-proxy.yaml.tpl, templates/prometheus-operator.yaml.tpl
Update ingresses with annotation `cloud-platform.justice.gov.uk/ignore-external-dns-weight:. These ingress are specific to cluster and will not have any weighted policy and hence ignore the check for aws-weight and set-identifier annotation
=> Update ingresses to ignore aws-weight annotation

templates/prometheus-operator.yaml.tpl
For io1 storage, the io1 to volume ratio should be 50:1. Prometheus pod pending to create with error `Failed to provision volume with StorageClass "io1-expand": InvalidParameterValue: Iops to volume size ratio of 266.666667 is too high; maximum is 50` and this PR fixes it.
=> Increase PV size to 750Gi for io1 storage

cloudwatch-exporter.tf
This goes from 0.10 to 0.12, should have no change for metrics, just dependencies updates: https://github.com/prometheus/cloudwatch_exporter/releases
=> upgrade CW exporter

metrics-server.tf
Why:
[Use bitnami helm chart for metrics_server#3411](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3411).
With reference to [the old helm chart](https://github.com/helm/charts/tree/master/stable/metrics-server) and [the replacement bitnami chart](https://github.com/bitnami/charts/tree/master/bitnami/metrics-server)
=> bitnami-helm-chart-for-metrics-server-3411

metrics-server.tf
When moving from stable chart to bitnami, the default values for apiService has changed. This results in the metrics api not available after the move and hence, couldnot get any pod metrics from the cluster.
This will create the apiService of metrics server.
=> Update values to create apiService

resources/prometheusrule-alerts/node-alerts.yaml
This is to trigger as warning(low-priority) when it is > 90
=> Update the Memory-High alert

resources/prometheusrule-alerts/application-alerts.yaml, templates/prometheus-operator-eks.yaml.tpl
Change PV alerts to notify the low-priority channel
Will now only notify PVs with owned by CP and not cluster wide PVs
=> Change PV alerts

README.md, cloudwatch-exporter.tf, grafana-role.tf, prometheus.tf, templates/cloudwatch-exporter.yaml, templates/prometheus-operator-eks.yaml.tpl
This PR has the following.
- Upgrade cloudwatch-exporter and iam-assumable-role-with-oidc used by cloudwatch-exporter
- Maintain IRSA(iam-assumable-role-with-oidc) module locally as the latest self assumed role has a dependency on terraform version
- Upgrade grafana
- Move grafana to the manager node group
- Upgrade grafana sidecar.
=> Upgrade grafana to latest

README.md, cloudwatch-exporter.tf, ecr-exporter.tf, prometheus.tf, variables.tf, versions.tf
This PR:
- replaces legacy dot syntax with square bracket notation
- removes legacy `//` comments with `#` comments
- removes unused variables `ingress_redirect` and `grafana_ingress_redirect_url`
- pins minimum provider versions
=> Refactor to meet standardised Terraform structure

templates/prometheus-operator-eks.yaml.tpl
Add AWS Node zone affinity for Prometheus Operator
This is to solve an issue on 1.23 where the pod does not get scheduled in the correct/same zone as the PV without having a zone affinity assigned.
=> Add AWS Node zone affinity for Prometheus Operator

resources/prometheusrule-alerts/application-alerts.yaml
Why:
[Kuberhealthy Alerts Review#4670](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4670)
Ammeded query to catch all namespace missing combinations (REGEX corrected):
`kuberhealthy_check{container="kuberhealthy",endpoint="http",exported_namespace="kuberhealthy",job="kuberhealthy",namespace="kuberhealthy",service="kuberhealthy",status!="1",error=~"Namespace check failed:missing namespaces:.+"}`
See:
1 missing namespace (velero)
[cp-0210-0717](https://prometheus.cp-0210-0717.cloud-platform.service.justice.gov.uk/graph?g0.expr=kuberhealthy_check%7Bcontainer%3D%22kuberhealthy%22%2Cendpoint%3D%22http%22%2Cexported_namespace%3D%22kuberhealthy%22%2Cjob%3D%22kuberhealthy%22%2Cnamespace%3D%22kuberhealthy%22%2Cservice%3D%22 …
=> alert-only-for-missing-namespaces-and-not-issues-with-kuberhealthy-itself

resources/prometheusrule-alerts/application-alerts.yaml
In response to the Prometheus server being oom killed, we need an alert to notify us beforehand so we can act and bump the size of the instance.
=> chore: 🤖 add prometheus server memory alert

templates/prometheus-operator-eks.yaml.tpl
This PR adds custom liveness and readiness probe to prometheus container.
The prometheus restarted few times in past days and while investigating its the readiness probe failed with 503. The prometheus is slow is responding sometimes due to having more data, more scrape and more serviceMonitors. Until we find the solution to handle, Increasing the timeoutSeconds from 3(default from chart) to 6 will allow slow prometheus to respond to probe before it is considered as failure.
This PR also changes the periodSeconds from 5 to 8 so the probe doesnt start before the previous one is finished.
=> Adjust liveness and readiness probe timout and periodseconds

resources/prometheusrule-alerts/application-alerts.yaml
Why:
[KuberhealthyOverallClusterStateCheck Alert - output information as to which of the Kuberhealthy alerts has failed#4844](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4844):
In my opinion we alerted by Kuberhealthy too much:
We have 4 Kuberhealthy checks:
1. **daemonset** - alert `KuberhealthyDaemonsetCheck`
2. **deployment**- alert `KuberhealthyDeploymentCheck`
3. **dns-status-internal** - alert `KuberhealthyDNSStatusCheckInternal`
4. **namespace-kh-check**- alert `KuberhealthyNamespaceExistsCheck`
For 1, 2 and 3 above, we are at present alerted twice (once for their respective alerts, plus the `KuberhealthyOverallClusterStateCheck` alert).
For 4 above. At present we mainly only get 1 alert - …
=> remove-superfluous-KuberhealthyOverallClusterStateCheck-alert

resources/prometheusrule-alerts/application-alerts.yaml
Sometimes Velero backup will fail (eg. volumes being deleted as the velero is backing up). We can't do much about these failures and we only need to know about them if they happen consistently which indicates a real issue.
=> chore: 🤖 velero alerts too sensitive

resources/prometheusrule-alerts/README.md, resources/prometheusrule-alerts/node-alerts.yaml
Adjusting this value and observing. Default garbage collection is triggered at 85% volume usage - the same value as this alert trigger. GC can require several attempts to free up space.
=> tweak low-priority rootvol high trigger value

prometheus.tf, proxy.tf
Relates to ministryofjustice/cloud-platform#4985
=> double helm release timeout for intermittent test cluster failures

templates/prometheus-operator-eks.yaml.tpl
this ensures 1.26 cluster upgrade will not introduce errors for kube-state-metrics `autoscaling/v2beta2` requests
=> bump kube-state-metrics image to v2.7.0

cloudwatch-exporter.tf, templates/cloudwatch-exporter.yaml
This is a minor version bump for the cloudwatch-exporter from 0.15.0 to 0.15.1
Info here - https://github.com/prometheus/cloudwatch_exporter/releases/tag/v0.15.1
=> Bump cloudwatch-exporter to 0.23.0 and add warn_on_empty_list_dimensions

templates/prometheus-operator-eks.yaml.tpl
Our current chart version is 56.21.4 and inside there, the [default `kube-state-metrics` chart is 2.10.1](https://github.com/prometheus-community/helm-charts/blob/fd6b0073754fcd0646ebe2c52662d62b15536c8c/charts/kube-state-metrics/values.yaml#L6) which is what is required for our [k8s version of 1.27](https://github.com/kubernetes/kube-state-metrics?tab=readme-ov-file#compatibility-matrix)
=> chore: 🤖 remove kube-state-metrics override pin

templates/prometheus-operator-eks.yaml.tpl
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3988
=> assiging max time for startup probe for WAL replay

templates/prometheus-operator-eks.yaml.tpl
Prometheus-server pod has affinity and schedule on its own node. The usage of cpu and memory is high and doesnt match the requests. Increase the cpu and memory to match the usual usage of the container.
This is also to check if this  reduces the WAL replay time during startup
=> Increase cpu, memory requests for prometheus pod to required usage

resources/prometheusrule-alerts/README.md, resources/prometheusrule-alerts/application-alerts.yaml, resources/prometheusrule-alerts/nginx-alerts.yaml, resources/prometheusrule-alerts/node-alerts.yaml
- Seperate nginx ingress controller related alerts to seperate Prometheus rule
- Fix ingress-controller queries to match the correct controller pod names
- Add alerts for production-only ingress 
- add new alert to measure ingress controller success rate - Related to: https://github.com/ministryofjustice/cloud-platform/issues/4886
=> Split Nginx alert into seperate PrometheusRule and fix expressions

resources/prometheusrule-alerts/nginx-alerts.yaml
This PR update the duration of success rate alert so it triggers of the rule condition persists over 10 minutes.
Having it as 5m is too sensitive and we get alerts when there is even a small minute blip.
Related to alert: https://mojdt.slack.com/archives/C8QR5FQRX/p1718277100533999 and https://mojdt.slack.com/archives/C8QR5FQRX/p1718277010938879
=> Adjust success rate alert to trigger for over 10m

templates/thanos-values.yaml.tpl
This is to test whether the compactor can dedup prom metrics pulled from a test cluster
https://thanos.manager.cloud-platform.service.justice.gov.uk/graph?g0.expr=kube_pod_container_info%7Bnamespace%3D%22starter-pack-0%22%2C%20container%3D~%22helloworld.*%22%2C%20clusterName%3D%22cp-1706-0722%22%7D&g0.tab=0&g0.stacked=1&g0.range_input=6h&g0.max_source_resolution=0s&g0.deduplicate=0&g0.partial_response=0&g0.store_matches=%5B%5D&g0.engine=thanos&g0.analyze=0
see here for info on the flag and background on vertical compaction https://thanos.io/tip/components/compact.md/#vertical-compactions
=> feat: 🎸 dedup series from the thanos compactor

templates/thanos-values.yaml.tpl
following the previous release, we try to dedup via enabling vertical compaction
https://thanos.io/tip/components/compact.md/#enabling-vertical-compaction
=> feat: 🎸 enable vertical compaction

prometheus.tf
relates to 
ministryofjustice/cloud-platform#5581
ministryofjustice/cloud-platform#5695
ministryofjustice/cloud-platform#5696
ministryofjustice/cloud-platform#5697
ministryofjustice/cloud-platform#5699
=> chore: 🤖 bump kube-prometheus-stack chart for k8s 1.28

templates/thanos-values.yaml.tpl
https://thanos.io/tip/components/query.md/#flags
- increase timeout to 5m
- and increase resource requests/ limits to cope with OOMKilled
```
Last State:     Terminated
Reason:       OOMKilled
Exit Code:    137
Started:      Fri, 23 Aug 2024 14:11:34 +0100
Finished:     Fri, 23 Aug 2024 14:15:37 +0100
Ready:          True
Restart Count:  9
Limits:
cpu:     1600m
memory:  24Gi
Requests:
cpu:        10m
memory:     100Mi
```
=> chore: 🤖 bump timeout for query

templates/thanos-values.yaml.tpl
We are seeing OOMKilled on this pod when we do big queries via thanos (the query will then fail)
https://grafana.live.cloud-platform.service.justice.gov.uk/d/6581e46e4e5c7ba40a07646395ef7b23/kubernetes-compute-resources-pod?var-datasource=default&var-cluster=&var-namespace=monitoring&var-pod=thanos-storegateway-0&orgId=1&refresh=10s&from=now-3h&to=now
=> chore: 🤖 bump mem limit thanos storegateway

templates/thanos-values.yaml.tpl
- once the compactor is finished with the backlog it will move on to downsampling
- set sensible downsampling values
- add wait flag
Below you can see once compactions backlog hit 0, the compactor just stopped, once it started again (green) it started compacting.
https://thanos.io/tip/components/compact.md/#downsampling
https://thanos.io/tip/operating/compactor-backlog.md/#detect-the-backlog
=> perf: ⚡️ prepare for downsampling phase of the compactor

templates/thanos-values.yaml.tpl
- downsample is pushing the baseline of files in vol up and then we are hitting the limit and causing compactor restarts
=> perf: ⚡️ bump vol size

prometheus.tf, templates/thanos-values.yaml.tpl
- bump kube-prometheus-stack `57.2.0 -> 66.2.1`
- reduce thanos downsample concurrency
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
https://github.com/prometheus-community/helm-charts/compare/kube-prometheus-stack-57.2.0...kube-prometheus-stack-66.2.1
https://github.com/prometheus-community/helm-charts/blob/4dd994bb37c905c522125dee319db4c6755f2a9d/charts/kube-prometheus-stack/Chart.yaml#L26
=> chore: 🤖 bump kube stack

README.md, locals.tf, subnet-exporter.tf, variables.tf
This PR adds aws-subnet-exporter to our monitoring stack, for subnet ip address availability metrics
[Repo](https://github.com/ministryofjustice/aws-subnet-exporter)
[Helm chart](https://github.com/ministryofjustice/cloud-platform-helm-charts/tree/main/aws-subnet-exporter)
=> Subnet exporter

README.md, templates/thanos-values.yaml.tpl
```
Instance Size 	vCPU 	Memory (GiB) 	
m6a.2xlarge 	8 	32
```
only workload on ng
=> perf: ⚡️ now compactor is on it's own ng we can bump limits

resources/prometheusrule-alerts/node-alerts.yaml
Added new alert for Node NotReady State as per the details in ticket https://github.com/orgs/ministryofjustice/projects/65/views/3?pane=issue&itemId=74458158&issue=ministryofjustice%7Ccloud-platform%7C6009
=> new alert added for Node NotReady State

README.md, templates/prometheus-operator-eks.yaml.tpl, templates/thanos-values.yaml.tpl, thanos.tf, variables.tf
- schedule in the monitoring group because it's so resource-hungry and can impact other services
- because the query can peak resources so high it makes sense to keep the query components separate so that they don't bring each other down
- increase replicas because it is [safe](https://thanos.io/v0.5/thanos/design.md/#scaling) for this component
- prevent thanos-query being deployed to a node which has prom on
=> perf: ⚡️ oomkilled on large queries

resources/manager_only_alerts.yaml
- the compactor works slowly we only need to be notified if thanos compactor is going up and not coming back down over long periods. The compactor goes up and down as part of it's standard behaviour when working on backlogs.
=> perf: ⚡️ reduce time frame for alert

main.tf
This is to facilitate permitted cloud-platform services executing queries against thanos endpoints
=> feat: 🎸 scope alerts ingress policy to include thanos services

templates/thanos-values.yaml.tpl
This pr is linked to issue https://github.com/orgs/ministryofjustice/projects/65?pane=issue&itemId=120717229&issue=ministryofjustice%7Ccloud-platform%7C7379
```
########################################
#
#
#
#
#
#
########################################
global:
security:
allowInsecureImages: true
```
=> change thanos image to legacy

resources/prometheusrule-alerts/README.md, resources/prometheusrule-alerts/node-alerts.yaml
Move scale up and down notification to #lower-priority-alerts
Create new alert that will alert when 3 or more nodes scale up/down within 30 minutes
Create new entry in README for change in node count 
Done as a part of: [#6997](https://github.com/ministryofjustice/cloud-platform/issues/6997)
=> Node scale alerts

templates/thanos-values.yaml.tpl
fix: 🐛 compact.concurrency is now helm native setting
remove from extra args to avoid double flag passing at deploy time
=> Concurrency as yaml

templates/thanos-values.yaml.tpl
To address high disk IO usage during compaction process (low priority alerts)
It looks like our concurrency value is much higher than typically recommended.
Docs suggest setting no of goroutines here to equal no of CPUs:
https://thanos.io/tip/components/compact.md/#cpu
compactor node group is using [m6a.2xlarge](https://aws.amazon.com/ec2/instance-types/m6a/#:~:text=Up%20to%2010-,m6a.2xlarge,-8)
=> chore: 🤖 set compact.concurrency to match available CPUs
