ministryofjustice/cloud-platform-terraform-monitoring

- README.md
- cloudwatch-exporter.tf
- Improved the README adding the enable variables 
- Updated the count to evaluate variable instead of checking the terraform workspace
> Improve doc and fix `count`

- prometheus.tf
- templates/prometheus-operator.yaml.tpl
- thanos.tf
- variables.tf
Added tolerations to the helm chart to to only run in nodes with taint `monitoring-node=true`
> Prometheus Operator tolerations

- templates/thanos-values.yaml.tpl
We want Thanos within the same node of Prometheus
> Added tolerations to Thanos store

- resources/cloudwatch-exporter.yaml
This ticket increases the scrape interval of cloudwatch to 2 minutes
> Cloudwatch exporter interval increase

- prometheus.tf
- templates/prometheus-operator.yaml.tpl
This upgrade is done in order to make the transition to Helm-3 possible.
> Upgraded to the latest Helm

- cloudwatch-exporter.tf
> Deleted dependence deploy cloudwatch-exporter

- resources/prometheusrule-alerts/node-alerts.yaml
Why:
[Fix Alert Runbook Links#2200](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2200)
Alert runbook_url link corrected
> runbook_url's corrected

- resources/prometheusrule-alerts/node-alerts.yaml
Why:
ticket
[[FIRING:1] :warning: CPU-High#2127](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2127)
Additional information about which pod
> add specific pod information re CPU High?Critical

- templates/oauth2-proxy.yaml.tpl
- templates/prometheus-operator.yaml.tpl
Reverts ministryofjustice/cloud-platform-terraform-monitoring#40
> Revert "Explicitly specified which ingress controller to use."

- prometheus.tf
- templates/oauth2-proxy.yaml.tpl
- templates/prometheus-operator.yaml.tpl
- In order to use our custom ingress controller we set custom ingress class
- Also cleaned up some old unused code
> Set custom ingress class

- resources/prometheusrule-alerts/README.md
Why:
ticket [warning: CPU-High#2127](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2127)
Additional investigation information for when this alert fires
> additional READme info for alert

- main.tf
Change NS annotation for Monitoring
> Change NS annotation for Monitoring

- templates/prometheus-operator.yaml.tpl
We are using a very old version ATM. Tested in `cp-1412-1020`
> Upgraded Thanos to latest

- main.tf
- prometheus.tf
- templates/oauth2-proxy.yaml.tpl
- templates/prometheus-operator.yaml.tpl
- variables.tf
https://github.com/ministryofjustice/cloud-platform/issues/2627
> dockerhub auth

- main.tf
- prometheus.tf
- templates/prometheus-operator.yaml.tpl
Major changes. Most probably breaking changes. Implemented already in Manager cluster and it looks alright.
> Prometheus Upgrade to latest

- templates/prometheus-operator.yaml.tpl
- This PR should close https://github.com/ministryofjustice/cloud-platform/issues/2695. 
- Tested in `cp-2501-1602`
> Added AlertManager data source to Prometheus

- .github/workflows/unit.yml
- test/unit-test/versions.tf
- versions.tf
This PR contains all changes in this repository made by the command `terraform 0.13upgrade` tool.
> Terraform 0.13 upgrade for repository

- cloudwatch-exporter.tf
- templates/cloudwatch-exporter.yaml
looks like we need at least https://github.com/prometheus/cloudwatch_exporter/releases/tag/cloudwatch_exporter-0.9.0 for Dynamo metrics
> newer cw exporter chart

- cloudwatch-exporter.tf
- ecr-exporter.tf
- Updated the SA name to the one defined in the values.yaml
- Remove the EKS conditionals
> Fix cloudwatch and ECR exporters to work with IRSA

- ecr-exporter.tf
Kiam is used for kops and irsa for eks
> Update ecr-exporter to enable irsa for eks only

- .github/workflows/unit.yml
- templates/thanos-values.yaml.tpl
- test/unit-test/main.tf
- test/unit-test/versions.tf
Received a high priority alarm about thanos compactor pv filling up to 99% when performing compacting. The size get reduced after the process but this is to avoid reaching the max and not able to do compacting.
> Increase pv size of thanos compactor as it is filling up to max 

- README.md
- outputs.tf
- prometheus.tf
- templates/prometheus-operator-eks.yaml.tpl
This is by using a separate helm_release resource
- create separate values file for eks using upgraded helm chart.
> Upgrade prometheus using latest version for EKS

- cloudwatch-exporter.tf
- ecr-exporter.tf
- locals.tf
- thanos.tf
This is with in the module as we have seperate helm release for eks
> Fix helm_release prometheus dependency

- README.md
- prometheus.tf
- templates/prometheus-operator-eks.yaml.tpl
Upgrade to 7.5 to fix IRSA in EKS
> upgrade Grafana

- prometheus.tf
- templates/prometheus-operator-eks.yaml.tpl
Upgrade Prometheus Operator form v20.0.1 to v30.0.1
> Upgrade Prometheus Operator to v30.0.1

- templates/prometheus-operator-eks.yaml.tpl
> more CPU/RAM

- README.md
- locals.tf
- prometheus.tf
- templates/oauth2-proxy.yaml.tpl
- templates/prometheus-operator-eks.yaml.tpl
- versions.tf
* unpin, not the place here
* change OIDC proxy chart source
* use ingress v1
* proxy now has a redis session store option
> Upgrade OIDC proxy

- README.md
- prometheus.tf
- proxy.tf
- test/unit-test/main.tf
- variables.tf
Add Ingress controller module dependencies for services which need ingress.
> Dependency for ingress-controller

- templates/cloudwatch-exporter.yaml
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4078
> Add clusterID option to allow filtering elasticache metrics by cluster

- README.md
- variables.tf
This is to provide this information while calling the module
> Update kibana_upsteam var

- templates/cloudwatch-exporter.yaml
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/4155
> Enable additional DynamoDB metrics

- templates/prometheus-operator-eks.yaml.tpl
- thanos.tf
Upgrade thanos to latest version
> Upgrade thanos to latest version

- templates/prometheus-operator-eks.yaml.tpl
This is to fix the dashboard not showing up.
Set labelValue  is set to "", as by default it is looking for "1"
> Fix grafana dashboard

- resources/prometheusrule-alerts/README.md
- resources/prometheusrule-alerts/node-alerts.yaml
Add node-scheduling-disabled alert for when a node has been cordoned or more than 3 hours
> Add node-scheduling-disabled alert

- resources/prometheusrule-alerts/README.md
> Fix Type in README

- templates/thanos-values.yaml.tpl
https://github.com/bitnami/charts/blob/main/bitnami/thanos/values.yaml#L2381
> Increase PV size of storegateway to accomodate increase time range

- resources/prometheusrule-alerts/node-alerts.yaml
Create change in node count notification
> Create change in node count notification

- prometheus.tf
- proxy.tf
- templates/oauth2-proxy.yaml.tpl
- templates/prometheus-operator-eks.yaml.tpl
Prometheus operator and proxy secrets set to sensitive Helm values
> Proxy sensitive values

- resources/prometheusrule-alerts/node-alerts.yaml
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4834
> Update ChangeInNodeCount message to get previous node count value

- templates/prometheus-operator-eks.yaml.tpl
whilst we investigate further issues with prometheus restarts
> Increase prometheus liveness and readiness probe values

- locals.tf
- prometheus.tf
- templates/prometheus-operator-eks.yaml.tpl
- templates/thanos-values.yaml.tpl
1/4 we need to pas the prom sa to thanos, parameterise the name in prep for the thanos upgrade.
https://github.com/bitnami/charts/tree/main/bitnami/thanos#to-1300
> chore: 🤖 parameterise prom sa

- templates/thanos-values.yaml.tpl
- thanos.tf
3/4 https://github.com/bitnami/charts/tree/main/bitnami/thanos#to-1500
> chore: 🤖 bump thanos

- templates/thanos-values.yaml.tpl
https://thanos.io/tip/components/compact.md/#vertical-compaction-use-cases
> feat: 🎸 --deduplication.func=penalty

- templates/thanos-values.yaml.tpl
The compactor is working but it's operating with a back log, increase  concurrency to work off the backlog quicker.
https://thanos.io/tip/operating/compactor-backlog.md/#solutions
> perf: ⚡️ increase concurrency to deal with backlog

- resources/prometheusrule-alerts/application-alerts.yaml
add thanos compactor cpu and mem alert to help catch when compactor is flapping
> Add thanos cpu and mem alert

- templates/thanos-values.yaml.tpl
let's try to keep the old data lying around as little as possible, as long as the data is compacted there is no reason to keep the original data around
> perf: ⚡️ we will be replicating data x3

- templates/prometheus-operator-eks.yaml.tpl
- templates/thanos-values.yaml.tpl
- increase prom replicas (one in each az)
- deduplicate the metrics at the query level
> Increase prom replicas

- templates/thanos-values.yaml.tpl
https://grafana.live.cloud-platform.service.justice.gov.uk/d/19fa341d-ae9d-4817-8a92-96b5df5ccd0a/thanos-overview?orgId=1&from=now-3h&to=now&refresh=5m
> perf: ⚡️ the compact backlog is a bit too flat

- templates/thanos-values.yaml.tpl
https://grafana.live.cloud-platform.service.justice.gov.uk/d/19fa341d-ae9d-4817-8a92-96b5df5ccd0a/thanos-overview?orgId=1&from=now-3d&to=now
> perf: ⚡️ increase concur to reduce backlog

- main.tf
relates to ministryofjustice/cloud-platform#5994
> chore: 🤖 cleanup redundant KIAM annotations

- templates/yace-cloudwatch-exporter.yaml
relates to ministryofjustice/cloud-platform#6277
> feat: 🎸 add elasticache DatabaseMemoryUsagePercentage metrics

- README.md
- proxy.tf
- variables.tf
relates to https://github.com/ministryofjustice/cloud-platform/issues/5121
> chore: 🤖 remove kibana proxy

- templates/yace-cloudwatch-exporter.yaml
relates to ministryofjustice/cloud-platform#6463
> feat: 🎸 add allocated storage metrics to RDS yace config

- README.md
- locals.tf
- rds-exporter.tf
- variables.tf
chore: 🤖 update irsa module name
chore: 🤖 bump resources
chore: 🤖 scrape interval and timeout setting
chore: 🤖 fix interval field naming
chore: 🤖 typo
> feat: 🎸 add rds-exporter chart

- templates/thanos-values.yaml.tpl
https://grafana.manager.cloud-platform.service.justice.gov.uk/d/919b92a8e8041bd567af9edab12c840c/kubernetes-persistent-volumes?from=now-7d&to=now&timezone=utc&var-datasource=P5DCFC7561CCDE821&var-cluster=&var-namespace=monitoring&var-volume=thanos-compactor&refresh=10s
> perf: ⚡️ 4tb -> 20tb

- README.md
- main.tf
relates to ministryofjustice/cloud-platform#5207
> feat: 🎸 add networkpolicy for internal alerts endpoints

- templates/thanos-values.yaml.tpl
> perf: ⚡️ OOMKilled when processing downsample

- README.md
- subnet-exporter.tf
- variables.tf
To make upcoming changes to the subnet exporter service less of a chore to upgrade
> chore: 🤖 allow passing of image tag via terraform var

- README.md
- prometheus.tf
- thanos.tf
- yace-cloudwatch-exporter.tf
bring iam module versions up to date
> Bump iam modules

- .github/workflows/documentation.yml
- .github/workflows/push-terraform-module-version.yaml
- .github/workflows/unit.yml
> Pin actions

- resources/prometheusrule-alerts/nginx-alerts.yaml
- exclude nginx non prod from high priority
> ci: 🎡 exclucde non prod ingress from high priority

- resources/prometheusrule-alerts/nginx-alerts.yaml
> perf: ⚡️ tweak nginx thresholds

- README.md
- ecr-exporter.tf
- prometheus.tf
- proxy.tf
- rds-exporter.tf
- subnet-exporter.tf
- versions.tf
relates to ministryofjustice/cloud-platform#7386
- Bumps helm provider to 3.0.2
- Refactors set_sensitive blocks
> feat: bump helm provider to 3.0.2

- README.md
- ecr-exporter.tf
- rds-exporter.tf
- subnet-exporter.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-irsa/releases/tag/2.1.0)
> chore: 🤖 updating irsa module calls

- resources/prometheusrule-alerts/node-alerts.yaml
Change alert severity to info to stop duplicate resolution notifications
> Change to info to stop multiple alerts
